fem_names = ['Abelita', 'Abigail', 'Acácia', 'Açucena', 'Ada', 'Adelaide', 'Adele', 'Adélia', 'Adelina', 'Adelinda', 'Adeline', 'Adelita', 'Adelma', 'Adília', 'Adilma', 'Adineia', 'Adoração', 'Adosinda', 'Adriana', 'Adriane', 'Adriele', 'Adrielly', 'Adrienne', 'Ágata', 'Agatha', 'Agda', 'Aglaia', 'Agna', 'Agnes', 'Águeda', 'Aida', 'Aidé', 'Aisha', 'Aixa', 'Alaíde', 'Alana', 'Alanis', 'Alba', 'Albana', 'Albanita', 'Alberta', 'Albertina', 'Albina', 'Alcina', 'Alcione', 'Alda', 'Aldina', 'Alegria', 'Alejandra', 'Alésia', 'Alessandra', 'Alessandrina', 'Alessia', 'Alexa', 'Alexandra', 'Alexandria', 'Alexandrina', 'Aléxia', 'Alexina', 'Aléxis', 'Ália', 'Aliana', 'Alice', 'Alícia', 'Alida', 'Alina', 'Aline', 'Alisia', 'Álison', 'Alissa', 'Alita', 'Alix', 'Alma', 'Althea', 'Altina', 'Aluísa', 'Alva', 'Alvina', 'Alyssa', 'Alzira', 'Amabília', 'Amada', 'Amália', 'Amanda', 'Amandina', 'Amara', 'Amarílis', 'Amber', 'Ambrósia', 'Ambrosina', 'Amélia', 'Amelie', 'Amena', 'América', 'Amira', 'Amora', 'Amparo', 'Amy', 'Ana', 'Anabel', 'Anabela', 'Anabelle', 'Anaíce', 'Anair', 'Anaíra', 'Anaís', 'Anaisa', 'Anaísa', 'Analice', 'Analisa', 'Analu', 'Anamar', 'Anastácia', 'Anastasia', 'Andrea', 'Andréa', 'Andreia', 'Andréia', 'Andreína', 'Andrelina', 'Andresa', 'Andresca', 'Andressa', 'Andreza', 'Ândria', 'Andrielly', 'Ane', 'Angel', 'Ângela', 'Angélica', 'Angelina', 'Angeline', 'Angelique', 'Angelita', 'Ânia', 'Anita', 'Annabel', 'Annabelle', 'Anouk', 'Antonela', 'Antonella', 'Antônia', 'Antonieta', 'Antonina', 'Anunciação', 'Anunciada', 'Any', 'Aparecida', 'Arabela', 'Araci', 'Argentina', 'Ária', 'Ariadna', 'Ariadne', 'Ariana', 'Ariane', 'Ariel', 'Ariela', 'Ariele', 'Arlene', 'Arlete', 'Arlinda', 'Armanda', 'Armandina', 'Arminda', 'Artemisa', 'Artemísia', 'Ashley', 'Ásia', 'Aspásia', 'Assunção', 'Assunta', 'Astrid', 'Atena', 'Athena', 'Augusta', 'Aura', 'Áurea', 'Aurélia', 'Aureliana', 'Aurora', 'Ausenda', 'Auxiliadora', 'Ava', 'Ayla', 
'Balbina', 'Bárbara', 'Bárbora', 'Bartolina', 'Basília', 'Basilisa', 'Basilissa', 'Beanina', 'Beatrice', 'Beatriz', 'Bebiana', 'Becky', 'Bela', 'Beladora', 'Belanice', 'Belanísia', 'Belara', 'Belarmina', 'Belém', 'Belenice', 'Belina', 'Belinda', 'Belisa', 'Belísia', 'Belita', 'Bella', 'Belle', 'Belmira', 'Benardete', 'Benedicta', 'Benedita', 'Benícia', 'Benigna', 'Benilde', 'Benita', 'Benjamina', 'Benvinda', 'Berengária', 'Berenice', 'Bernadete', 'Bernadette', 'Bernarda', 'Bernardete', 'Bérnia', 'Berta', 'Bertha', 'Bertila', 'Bertilde', 'Bertina', 'Betânia', 'Beth', 'Bétia', 'Betina', 'Betsabé', 'Betsy', 'Betty', 'Bia', 'Bianca', 'Bibiana', 'Bina', 'Blanche', 'Blandina', 'Blásia', 'Bonifácia', 'Bonnie', 'Branca', 'Brásia', 'Brázia', 'Brena', 'Brenda', 'Briana', 'Brícia', 'Brida', 'Bridget', 'Brígida', 'Brigite', 'Brisa', 'Brites', 'Brízida', 'Bruna', 'Brunilde', 
'Cacelina', 'Cácia', 'Cacilda', 'Caetana', 'Caia', 'Caila', 'Cailane', 'Cailany', 'Caitiane', 'Camélia', 'Camila', 'Camille', 'Camilly', 'Candelária', 'Candice', 'Cândida', 'Carela', 'Cáren', 'Cárin', 'Carina', 'Carine', 'Carisa', 'Carísia', 'Carissa', 'Carla', 'Carlinda', 'Carlota', 'Carma', 'Carmel', 'Carmela', 'Carmélia', 'Carmelina', 'Carmelinda', 'Carmelita', 'Cármen', 'Carmezinda', 'Carmina', 'Carminda', 'Carminho', 'Carol', 'Carole', 'Carolina', 'Caroline', 'Cassandra', 'Cássia', 'Cassilda', 'Casta', 'Catalina', 'Catarina', 'Caterina', 'Catharine', 'Catherine', 'Cátia', 'Cecília', 'Celeste', 'Célia', 'Celina', 'Celine', 'Celinia', 'Celisia', 'Celsa', 'Cereja', 'Ceres', 'Cesaltina', 'Cesária', 'Cesarina', 'Chantal', 'Charlene', 'Cheila', 'Chema', 'Chenoa', 'Chiara', 'Chloe', 'Christiana', 'Christiane', 'Ciara', 'Cibele', 'Cibelly', 'Cidália', 'Cidalina', 'Cidalisa', 'Cinara', 'Cinderela', 'Cindy', 'Cinira', 'Cíntia', 'Cipora', 'Circe', 'Círia', 'Cirila', 'Cita', 'Cizina', 'Clara', 'Clarice', 'Clarina', 'Clarinda', 'Clarinha', 'Clarissa', 'Clarisse', 'Cláudia', 'Claudiana', 'Claudina', 'Cleia', 'Cleide', 'Cleidiane', 'Clélia', 'Clemência', 'Clementina', 'Cléo', 'Cleodice', 'Cleonice', 'Cleópatra', 'Clésia', 'Cleyde', 'Clícia', 'Climénia', 'Clívia', 'Cloe', 'Cloé', 'Clorinda', 'Clotilde', 'Colete', 'Conceição', 'Consolação', 'Constança', 'Constância', 'Consuelo', 'Cora', 'Corália', 'Coralina', 'Cordélia', 'Corina', 'Corine', 'Córita', 'Cornélia', 'Cosete', 'Cremilda', 'Cremilde', 'Cris', 'Crisália', 'Crisálida', 'Crisanta', 'Crisante', 'Cristal', 'Cristela', 'Cristele', 'Cristene', 'Cristiana', 'Cristiane', 'Cristina', 'Cristolinda', 'Custódia', 'Cynthia', 'Dacelina', 'Daci', 'Dádiva', 'Dafne', 'Dagmar', 'Daiana', 'Daiane', 'Daina', 'Daine', 'Daisi', 'Daisy', 'Dália', 'Daliana', 'Dalila', 'Dalinda', 'Dalira', 'Dalma', 'Dalmara', 'Dalva', 'Damaris', 'Dana', 'Dandara', 'Dânia', 'Daniana', 'Daniela', 'Danielle', 'Danielly', 'Danila', 'Danis', 'Dara', 'Darci', 'Darcília', 'Darcy', 'Darlene', 'Dayane', 'Débora', 'Deborah', 'Dejanira', 'Delfina', 'Delma', 'Demétria', 'Denisa', 'Denise', 'Deolinda', 'Deonilde', 'Deotília', 'Dercy', 'Desiré', 'Deusa', 'Dialina', 'Diana', 'Digna', 'Dilar', 'Diliana', 'Dilma', 'Dilsa', 'Dina', 'Diná', 'Dinah', 'Dinara', 'Dinora', 'Dinorah', 'Dionia', 'Dionísia', 'Dirce', 'Diva', 'Dolores', 'Domênica', 'Domicília', 'Domingas', 'Dominica', 'Dona', 'Donatela', 'Donatella', 'Donna', 'Dora', 
'Doralice', 'Dores', 'Dóris', 'Doroteia', 'Dorothea', 'Dulce', 'Dulcina', 'Dulcineia', 'Ecila', 'Eden', 'Edênia', 'Edilene', 'Edina', 'Edite', 'Edith', 'Edna', 'Edneia', 'Eduarda', 'Edvânia', 'Edviges', 'Eglantina', 'Elaine', 'Elana', 'Elba', 'Eleanor', 'Electra', 'Eleine', 'Elena', 'Eleonor', 'Eleonora', 'Élia', 'Eliana', 'Eliane', 'Élin', 'Elina', 'Elis', 'Élis', 'Elisa', 'Elisabeta', 'Elisabete', 'Elisabeth', 'Elisângela', 'Elisete', 'Elizabete', 'Ellen', 'Elma', 'Elmina', 'Eloá', 'Eloah', 'Eloisa', 'Eloísa', 'Eloise', 'Elsa', 'Elvira', 'Elza', 'Ema', 'Emanuela', 'Emanuelle', 'Emília', 'Emiliana', 'Emily', 'Emma', 'Encarnação', 'Eneida', 'Engrácia', 'Eponina', 'Ercília', 'Érica', 'Erika', 'Éris', 'Esmeralda', 'Esperança', 'Estéfana', 'Estefani', 'Estefânia', 'Estela', 'Ester', 'Esther', 'Estrela', 'Eudora', 'Eufêmia', 'Eugênia', 'Eulália', 'Eunice', 'Eurica', 'Eva', 'Evangelina', 'Evelin', 'Evelina', 'Eveline', 'Evelyn', 'Excelsa', 
'Fábia', 'Fabiana', 'Fabíola', 'Fabrícia', 'Fabrízia', 'Fani', 'Fara', 'Fátima', 'Federica', 'Fedora', 'Fedra', 'Felícia', 'Feliciana', 'Felicidade', 'Felipa', 'Felisbela', 'Fernanda', 'Fernandina', 'Fidélia', 'Filipa', 'Filomena', 'Fiona', 'Firmina', 'Flávia', 'Flor', 'Flora', 'Florbela', 'Florença', 'Florência', 'Florentina', 'Florinda', 'Formosa', 'Franca', 'Franciele', 'Franciely', 'Francília', 'Francine', 'Francisca', 'Frederica', 
'Gabriela', 'Gabriele', 'Gabrieli', 'Gaetana', 'Gaia', 'Galdência', 'Galdina', 'Gardênia', 'Gasparina', 'Gemma', 'Generosa', 'Genezia', 'Genoveva', 'Genuzia', 'Georgete', 'Geórgia', 'Georgiana', 'Georgina', 'Geovana', 'Geralda', 'Gertrudes', 'Gerusa', 'Geruza', 'Giana', 'Gilda', 'Gina', 'Gioconda', 'Giovana', 'Giovanna', 'Girlene', 'Gisela', 'Gisele', 'Giselle', 'Gislaine', 'Gisleine', 'Gislene', 'Giulia', 'Giuliana', 'Gladys', 'Glaúcia', 'Glenda', 'Glicéria', 'Glória', 'Gonzaga', 'Graça', 'Graciela', 'Gracília', 'Gracinda', 'Graziela', 'Graziele', 'Grazielly', 'Guadalupe', 'Guilhermina', 'Guiomar', 
'Hadassa', 'Haidé', 'Hannah', 'Hayla', 'Hebe', 'Hedviges', 'Helen', 'Helena', 'Heloísa', 'Heloise', 'Henriqueta', 'Hera', 'Hilary', 'Hilda', 
'Iara', 'Iasmin', 'Iasmine', 'Ida', 'Idalina', 'Ilda', 'Imaculada', 'Inácia', 'Inara', 'India', 'Indina', 'Inês', 'Ingrid', 'Iolanda', 'Ioná', 'Ione', 'Iracema', 'Irene', 'Irenilda', 'Iria', 'Irina', 'Íris', 'Isabel', 'Isabela', 'Isabeli', 'Isabella', 'Isadora', 'Isaura', 'Isidora', 'Isis', 'Ismara', 'Isolda', 'Ítala', 'Ivana', 'Ivandra', 'Ivani', 'Ivete', 'Ivone', 'Ivonete', 'Ivy', 'Izabel', 'Izaira', 
'Jaciane', 'Jaciara', 'Jacinta', 'Jacira', 'Jacirene', 'Jacobina', 'Jacqueline', 'Jade', 'Jamila', 'Janaína', 'Jandira', 'Jane', 'Janete', 'Jani', 'Janice', 'Janilce', 'Janina', 'Janine', 'Jaqueline', 'Jasmim', 'Jasmin', 'Jeane', 'Jeni', 'Jénifer', 'Jennifer', 'Jerusa', 'Jéssica', 'Joana', 'Joelly', 'Joelma', 'Joice', 'Jorgina', 'Joseane', 'Josefa', 'Josefina', 'Joselene', 'Joselina', 'Josiane', 'Jossara', 'Josuana', 'Joyce', 'Jucele', 'Jucélia', 'Juciele', 'Juciene', 'Judite', 'Judith', 'Júlia', 'Juliana', 'Juliane', 'Julie', 'Julieta', 'Juraci', 'Jurema', 'Jussara', 'Jussara', 
'Kaline', 'Kamila', 'Kamile', 'Kamily', 'Karen', 'Karina', 'Karine', 'Karla', 'Karol', 'Karolina', 'Karoline', 'Katarina', 'Katharina', 'Kathelyn', 'Kathleen', 'Katia', 'Kátia', 'Kauane', 'Kauani', 'Kauany', 'Kayanne', 'Kayla', 'Kaylane', 'Keila', 'Kelly', 'Kelma', 'Késia', 'Keyla', 'Kiara', 'Kim', 'Kimberly', 'Kristin', 'Kyara', 
'Laiane', 'Laila', 'Laira', 'Laís', 'Laisa', 'Lana', 'Lara', 'Larissa', 'Lauany', 'Laura', 'Lauryn', 'Lavínia', 'Layane', 'Layla', 'Layra', 'Lea', 'Léa', 'Leah', 'Leana', 'Leandra', 'Leda', 'Lediane', 'Leia', 'Leila', 'Leilani', 'Lélia', 'Lena', 'Leni', 'Leona', 'Leônia', 'Leonor', 'Leonora', 'Leslie', 'Letícia', 'Letízia', 'Leya', 'Lia', 'Liana', 'Liane', 'Liara', 'Liara', 'Lícia', 'Lídia', 'Lidiane', 'Lígia', 'Lília', 'Lilian', 'Liliana', 'Liliane', 'Lina', 'Linda', 'Lindalva', 'Lira', 'Lis', 'Lisa', 'Lisandra', 'Livânia', 'Lívia', 'Liz', 'Liza', 'Lohana', 'Lohane', 'Lola', 'Lorany', 'Lorena', 'Lorenza', 'Lorraine', 'Louise', 'Lua', 'Luana', 'Luane', 'Luara', 'Lucélia', 'Lucena', 'Lúcia', 'Luciana', 'Luciane', 'Luciene', 'Lucília', 'Lucrécia', 'Lucy', 'Ludmila', 'Luísa', 'Luiza', 'Luma', 'Lumena', 'Luna', 'Lurdes', 'Luz', 'Luzia', 'Luzinira', 'Lusitânia', 'Lyra', 
'Mabel', 'Mabelly', 'Macy', 'Madalena', 'Madel', 'Mae', 'Maeva', 'Mafalda', 'Magali', 'Magda', 'Maia', 'Maiara', 'Maira', 'Maíra', 'Maísa', 'Maitê', 'Malena', 'Malu', 'Malvina', 'Manoela', 'Manon', 'Manuela', 'Mar', 'Mara', 'Marcela', 'Márcia', 'Margarida', 'Maria', 'Mariáh', 'Mariana', 'Maribel', 'Marie', 'Marieta', 'Marilda', 'Marileide', 'Marilene', 'Marília', 'Marilza', 'Marina', 'Marisa', 'Marise', 'Marisol', 'Maristela', 'Mariza', 'Marjolene', 'Marjorie', 'Marlene', 'Marli', 'Marlisa', 'Marlise', 'Marly', 'Marta', 'Martha', 'Martina', 'Mary', 'Mathilda', 'Matilda', 'Matilde', 'Maura', 'Máxima', 'Maya', 'Mayara', 'Mayla', 'Mayra', 'Mayse', 'Mel', 'Mélanie', 'Mélcia', 'Melina', 'Melinda', 'Melissa', 'Mercedes', 'Mia', 'Micaela', 'Michele', 'Michelle', 'Mila', 'Milagres', 'Milena', 'Mirela', 'Mirella', 'Miriã', 'Miriam', 'Moema', 'Moira', 'Mônica', 'Monique', 'Monise', 'Morena', 'Morgana', 'Muriel', 'Muriela', 'Myriam', 
'Nádia', 'Nadine', 'Nadir', 'Nadja', 'Naiara', 'Naíde', 'Nair', 'Nancy', 'Naomi', 'Nara', 'Naraiana', 'Narci', 'Narcisa', 'Natacha', 'Natália', 'Natalina', 'Natasha', 'Nathaly', 'Nathiely', 'Natielly', 'Nauria', 'Nayane', 'Nayara', 'Nayla', 'Nayra', 'Nazaré', 'Neci', 'Neida', 'Neide', 'Neize', 'Neli', 'Nélia', 'Nelma', 'Nelsa', 'Nely', 'Nereida', 'Neusa', 'Neuza', 'Neyde', 'Nice', 'Nicole', 'Nídia', 'Nilma', 'Nilsa', 'Nilse', 'Nilza', 'Nina', 'Nita', 'Nívea', 'Nízia', 'Noa', 'Noélia', 'Noemi', 'Noémia', 'Norah', 'Norberta', 'Norlise', 'Norma', 'Núbia', 'Núria', 
'Oceana', 'Odaria', 'Odete', 'Odineide', 'Ofélia', 'Olália', 'Olga', 'Olímpia', 'Olívia', 'Ondina', 'Oriana', 'Orlandina', 'Ortelina', 'Osmarina', 'Osneide', 'Otília', 'Ozeneide', 
'Padma', 'Palmira', 'Paloma', 'Pamela', 'Pandora', 'Paola', 'Paquita', 'Patrícia', 'Patty', 'Paula', 'Paulina', 'Pauline', 'Paz', 'Pedrina', 'Penélope', 'Penha', 'Perla', 'Pérola', 'Perpétua', 'Pérsia', 'Pétala', 'Petra', 'Petula', 'Petúnia', 'Philippa', 'Piedade', 'Pietra', 'Pilar', 'Poliana', 'Poppy', 'Primavera', 'Priscila', 
'Quezia', 'Quinn', 'Quintina', 'Quirina', 'Quitéria', 
'Rachel', 'Radija', 'Rafaela', 'Raica', 'Raimunda', 'Raina', 'Raisa', 'Raissa', 'Ramona', 'Ranielle', 'Raphaela', 'Raquel', 'Ravena', 'Rayane', 'Rayssa', 'Rebeca', 'Rebeka', 'Regiane', 'Regina', 'Reina', 'Rejane', 'Renata', 'Renée', 'Rhianna', 'Rhonda', 'Risoleta', 'Rita', 'Roberta', 'Robin', 'Rogéria', 'Romilda', 'Romy', 'Rosa', 'Rosalba', 'Rosália', 'Rosalice', 'Rosalina', 'Rosana', 'Rosane', 'Rosângela', 'Rosário', 'Rosaura', 'Rose', 'Roseane', 'Roseli', 'Roselyn', 'Rosemar', 'Rosemary', 'Rosiane', 'Rosilda', 'Rosilene', 'Rosinete', 'Rosita', 'Roxane', 'Rúbia', 'Rubina', 'Ruby', 'Rute', 'Ruth', 
'Sabina', 'Sabine', 'Sabrina', 'Sacha', 'Safira', 'Sahara', 'Salete', 'Sally', 'Salomé', 'Samanta', 'Samantha', 'Samara', 'Sami', 'Samia', 'Samira', 'Sância', 'Sandra', 'Sandrina', 'Sandy', 'Sansa', 'Sara', 'Sarah', 'Sari', 'Sasha', 'Savana', 'Savanah', 'Scarlett', 'Selena', 'Selene', 'Selina', 'Selma', 'Seomara', 'Serafina', 'Seraphina', 'Serena', 'Severina', 'Sharon', 'Sheila', 'Shirley', 'Siena', 'Sienna', 'Sierra', 'Silene', 'Silvana', 'Sílvia', 'Simara', 'Simone', 'Sofia', 'Sol', 'Solana', 'Solange', 'Solene', 'Sônia', 'Sonya', 'Sophia', 'Sophie', 'Soraia', 'Soraya', 'Stacy', 'Stela', 'Stella', 'Stephanie', 'Suéli', 'Suki', 'Suri', 'Suria', 'Surya', 'Susana', 'Suzana', 'Suzy', 'Sydney', 'Sylvia', 
'Tabita', 'Taciana', 'Taila', 'Tainá', 'Tainara', 'Tais', 'Taís', 'Taísa', 'Taíssa', 'Talia', 'Talita', 'Talullah', 'Tamar', 'Tamara', 'Tamára', 'Tâmara', 'Tânia', 'Tássia', 'Tatiana', 'Tatiane', 'Tauane', 'Tauany', 'Tayla', 'Tayná', 'Taynara', 'Telma', 'Teodora', 'Teresa', 'Teresinha', 'Tereza', 'Thabata', 'Thabita', 'Thaila', 'Thaís', 'Thaíssa', 'Thalia', 'Thalita', 'Theodora', 'Thuanny', 'Thuyla', 'Ticiana', 'Tiffany', 'Tulane', 
'Urânia', 'Uriela', 'Úrsula', 
'Valdete', 'Valência', 'Valentina', 'Valéria', 'Valerie', 'Valesca', 'Valquíria', 'Vanda', 'Vanessa', 'Vânia', 'Vanina', 'Vanusa', 'Vanuza', 'Veja', 'Velma', 'Venice', 'Vênus', 'Venusa', 'Vera', 'Verena', 'Veridiana', 'Verônica', 'Vicenzia', 'Vicky', 'Victória', 'Vida', 'Vienna', 'Vilma', 'Violante', 'Violet', 'Violeta', 'Virgínia', 'Vitória', 'Vivian', 'Viviana', 'Viviane', 'Vivienne', 
'Wanda', 'Wanessa', 'Wendy', 'West', 'Whitney', 'Willa', 'Willow', 'Wilma', 'Winnie', 
'Xandra', 'Xena', 'Xenia', 'Ximena', 'Xiomara', 
'Yael', 'Yane', 'Yara', 'Yasmin', 'Yngrid', 'Yohanna', 'Yolanda', 'Ysabel', 'Ysabella', 'Yvette', 'Yvone', 
'Zahra', 'Zaira', 'Zaira', 'Zamy', 'Zara', 'Zará', 'Zarina', 'Zayda', 'Zeferina', 'Zélia', 'Zelinda', 'Zelma', 'Zena', 'Zenaida', 'Zenaide', 'Zénia', 'Zila', 'Zilá', 'Zilda', 'Zília', 'Zilma', 'Zínia', 'Zita', 'Ziza', 'Zoa', 'Zobaida', 'Zoe', 'Zoé', 'Zola', 'Zora', 'Zoraida', 'Zubaida', 'Zubeida', 'Zulaia', 'Zuleica', 'Zuleima', 

'Adalgisa', 'Adelia', 'Allana', 'Arquimina', 'Bele', 'Blenda', 'Brigida', 'Capitu', 'Carmen', 'Carlene', 'Charlotte', 'Cinthia', 'Cleydiane', 'Damiana', 'Dariana', 'Dayse', 'Déborah', 'Deise', 'Désirée', 'Dominique', 'Dorcas', 'Eleonara', 'Eliza', 'Emanuele', 'Emilly', 'Esthefany', 'Estella', 'Evelyne', 'Fabiane', 'Fanny', 'Felicita', 'Fiorella', 'Flaviane', 'Franceline', 'Francesca', 'Francis', 'Gabriella', 'Gabrielle', 'Gabrielly', 'Gabriely', 'Gaby', 'Geísa', 'Géssica', 'Gilene', 'Gilmara', 'Glaucia', 'Gleice', 'Goreti', 'Grace', 'Greice', 'Hagata', 'Haidê', 'Hana', 'Hanna', 'Harumi', 'Heidi', 'Heike', 'Helene', 'Helenice', 'Hellen', 'Heloíse', 'Hercília', 'Hérica', 'Hermínia', 'Hermione', 'Hildebora', 'Hortênsia', 'Hulda', 'Iris', 'Irisneide', 'Isabelle', 'Isabelly', 'Ivanova', 'Iza', 'Izadora', 'Izaura', 'Izaurina', 'Jaine', 'Jamile', 'Jamilly', 'Janaina', 'Jasmine', 'Jenifer', 'Jezabel', 'Jordana', 'Kaila', 'Kaliana', 'Kalina', 'Kamilly', 'Katerine', 'Katherine', 'kathleen', 'Katy', 'Kéfera', 'Kemilly', 'Ketlyn', 'Lady', 'Leidiana', 'Leoni', 'Leonia', 'Marcena', 'Mariah', 'Mariane', 'Mariene', 'Marialda', 'Naara', 'Nabi', 'Nabor', 'Nadya', 'Naila', 'Nájela', 'Najma', 'Nana', 'Nani', 'Naoko', 'Násser', 'Nayana', 'Niara', 'Nisha', 'Nívia', 'Nora', 'Obede', 'Octávia', 'Olinda', 'Orlanda', 'Perpetua', 'Pollyana', 'Potira', 'Potira', 'Quésia', 'Quenia', 'Queila', 'Quizla', 'Quizlaine', 'Queren', 'Raís', 'Regilene', 'Rojelma', 'Rosires', 'Sita', 'Somia', 'Sonja', 'Stefany', 'Suellen', 'Sulamita', 'Susane', 'Suzane', 'Suzanny', 'Suzany', 'Suzi', 'Tábata', 'Taiane', 'Tália', 'Tamires', 'Tamiris', 'Tarsila', 'Terezinha', 'Tirza', 'Thainá', 'Thamires', 'Thayla', 'Thayná', 'Thaynara', 'Thays', 'Urlaine', 'Ully', 'Uvy', 'Uyara', 'Uynara', 'Uiara', 'Uinara', 'Urbi', 'Uda', 'Ulda', 'Uaná', 'Valdinéia', 'Valdirene', 'Valentine', 'Vanderleia', 'Vanilda', 'Vasti', 'Vicki', 'Violetta', 'Wesla', 'Wilda', 'Wildane', 'Wilikilia', 'Wilmara', 'Wismara', 'Yanni', 'Yannis', 'Yasmim', 'Yasmine', 'Yelena', 'Yeva', 'Yona', 'Yves', 'Yvi', 'Zafira', 'Zahara', 'Zahirah', 'Zaida', 'Zelina', 'Zenine', 'Zion', 'Zulmira', 
'Acacia', 'Adilia', 'Agata', 'Agueda', 'Aide', 'Alaide', 'Alesia', 'Alexia', 'Alexis', 'Alia', 'Alicia', 'Alison', 'Aluisa', 'Amabilia', 'Amalia', 'Amarilis', 'Ambrosia', 'Amelia', 'America', 'Anaice', 'Anaira', 'Anais', 'Anastacia', 'Andreina', 'Angelica', 'Aria', 'Artemisia', 'Asia', 'Aspasia', 'Aurea', 'Aurelia', 'Barbara', 'Barbora', 'Basilia', 'Belanisia', 'Belem', 'Belisia', 'Benicia', 'Berengaria', 'Bernia', 'Betia', 'Betsabe', 'Blasia', 'Bonifacia', 'Brasia', 'Brazia', 'Bricia', 'Brizida', 'Cacia', 'Camelia', 'Candelaria', 'Caren', 'Carin', 'Carisia', 'Carmelia', 'Cassia', 'Catia', 'Cecilia', 'Celia', 'Cesaria', 'Cidalia', 'Cintia', 'Ciria', 'Claudia', 'Clelia', 'Cleo', 'Cleopatra', 'Clesia', 'Clicia', 'Climenia', 'Clivia', 'Coralia', 'Cordelia', 'Corita', 'Cornelia', 'Crisalia', 'Crisalida', 'Custodia', 'Dadiva', 'Dalia', 'Darcilia', 'Debora', 'Demetria', 'Deotilia', 'Desire', 'Dionisia', 'Domicilia', 'Doris', 'Elia', 'Elin', 'Eloa', 'Emilia', 'Engracia', 'Ercilia', 'Erica', 'Eris', 'Estefana', 'Eulalia', 'Fabia', 'Fabiola', 'Fabricia', 'Fabrizia', 'Fatima', 'Felicia', 'Fidelia', 'Flavia', 'Francilia', 'Georgia', 'Gliceria', 'Gloria', 'Gracilia', 'Haide', 'Heloisa', 'Inacia', 'Iona', 'Itala', 'Jessica', 'Jucelia', 'Julia', 'Kesia', 'Lais', 'Lavinia', 'Lelia', 'Leticia', 'Letizia', 'Licia', 'Lidia', 'Ligia', 'Lilia', 'Livia', 'Lucelia', 'Lucia', 'Lucilia', 'Lucrecia', 'Luisa', 'Maisa', 'Marcia', 'Marilia', 'Maxima', 'Melanie', 'Melcia', 'Nadia', 'Naide', 'Natalia', 'Nazare', 'Nelia', 'Nidia', 'Nivea', 'Nizia', 'Noelia', 'Noemia', 'Nubia', 'Nuria', 'Ofelia', 'Olalia', 'Olimpia', 'Olivia', 'Otilia', 'Patricia', 'Penelope', 'Perola', 'Persia', 'Petala', 'Petunia', 'Quiteria', 'Renee', 'Rogeria', 'Rosalia', 'Rosario', 'Rubia', 'Salome', 'Silvia', 'Sueli', 'Taina', 'Taisa', 'Taissa', 'Tassia', 'Tayna', 'Thaissa', 'Ursula', 'Valeria', 'Valquiria', 'Victoria', 'Virginia', 'Zelia', 'Zenia', 'Zilia', 'Zinia', 'Desiree', 'Geisa', 'Gessica', 'Hercilia', 'Herica', 'Herminia', 'Kefera', 'Najela', 'Nasser', 'Nivia', 'Octavia', 'Quesia', 'Rais', 'Tabata', 'Thais', 'Thaina', 'Thayna', 'Uana', 'Valdineia', 'Vitoria', 
'Anna', 'Camilla', 'Daniella', 'Diane', 'Dianne', 'Driana', 'Duda', 'Evellyn', 'Francielle', 'Francielly', 'Gleyce', 'Heloiza', 'Heloíza', 'Iana', 'Ianna', 'Iule', 'Iulle', 'Jeny', 'Jheni', 'Jheny', 'Jenni', 'Jenny', 'Jhenni', 'Jhenny', 'Karinna', 'Lauara', 'Luíza', 'Millena', 'Mylena', 'Myllena', 'Natalie', 'Nicolle', 'Nicholly', 'Nikolly', 'Priscilla', 'Raffaela', 'Rebecca', 'Stephany', 'Stéphanie', 'Whendy', 
# apelidos frequentes demais
'Manu', 'Jessy', 'Lari', 'Yas', 'Day', 'Isa', 'Let'

]


male_names = ['Aaron', 'Abel', 'Abelardo', 'Abelino', 'Abiel', 'Abiezer', 'Abílio', 'Abner', 'Abraão', 'Acácio', 'Adailton', 'Adair', 'Adalberto', 'Adalgiso', 'Adalício', 'Adalmir', 'Adalto', 'Adam', 'Adamastor', 'Adamor', 'Adão', 'Adeci', 'Adeildo', 'Adelair', 'Adélcio', 'Adelino', 'Adélio', 'Adelson', 'Ademar', 'Ademilson', 'Ademir', 'Aderbal', 'Adérito', 'Adilson', 'Admilson', 'Adolfo', 'Adonai', 'Adonis', 'Adónis', 'Adrian', 'Adriano', 'Adriel', 'Aécio', 'Afonso', 'Afrânio', 'Agenor', 'Ageo', 'Agipino', 'Agnaldo', 'Agnelo', 'Agostinho', 'Aguinaldo', 'Ailton', 'Aires', 'Airton', 'Aitor', 'Alair', 'Alan', 'Alaôr', 'Alarico', 'Albano', 'Albertino', 'Alberto', 'Albino', 'Alcides', 'Alcindo', 'Aldair', 'Aldemir', 'Aldenor', 'Aldo', 'Alejandro', 'Alessandro', 'Alex', 'Alexandre', 'Alexandrino', 'Alexandro', 'Aléxio', 'Aléxis', 'Alfredo', 'Alípio', 'Alírio', 'Alison', 'Allan', 'Almerindo', 'Almir', 'Aloísio', 'Alonzo', 'Altino', 'Aluísio', 'Alvantino', 'Álvaro', 'Alvino', 'Amadeo', 'Amadeu', 'Amândio', 'Amarildo', 'Amauri', 'Amaury', 'Ambrósio', 'Américo', 'Amílcar', 'Amilton', 'Amir', 'Ananias', 'Andersen', 'Anderson', 'André', 'Ândreo', 'Andrés', 'Anésio', 'Angélico', 'Ângelo', 'Aníbal', 'Anísio', 'Anselmo', 'Antenor', 'Antero', 'Anthony', 'Antônio', 'Apollo', 'Apolo', 'Aprígio', 'Aquiles', 'Arcanjo', 'Ari', 'Ariel', 'Aristeu', 'Aristides', 'Armando', 'Armindo', 'Arnaldo', 'Aron', 'Arthur', 'Artur', 'Arturo', 'Ary', 'Asher', 'Assis', 'Ataíde', 'Athos', 'Átila', 'Atlas', 'Augusto', 'Aureliano', 'Aurelino', 'Aurélio', 'Aurino', 'Ayrton', 
'Balbino', 'Balduíno', 'Baltasar', 'Baltazar', 'Barnabé', 'Bartolomeu', 'Basileu', 'Basílio', 'Batista', 'Belarmino', 'Belchior', 'Belisário', 'Belmiro', 'Bendito', 'Benedito', 'Benício', 'Benito', 'Benjamim', 'Benjamin', 'Bento', 'Bernardo', 'Beto', 'Bill', 'Boanerges', 'Bob', 'Bonifácio', 'Bóris', 'Bosco', 'Brandon', 'Breno', 'Brian', 'Bruce', 'Bruno', 'Bryan', 'Byron', 
'Cacildo', 'Cadú', 'Cael', 'Caetano', 'Caíco', 'Caio', 'Caíque', 'Calazan', 'Caleb', 'Calisto', 'Calixto', 'Calvin', 'Camilo', 'Cândido', 'Canuto', 'Carlos', 'Casimiro', 'Cassiano', 'Cássio', 'Castiel', 'Cauã', 'Cauê', 'Celestino', 'Celso', 'César', 'Charles', 'Christian', 'Christian', 'Christopher', 'Cícero', 'Cid', 'Cirilo', 'Ciro', 'Cláudio', 'Claus', 'Clayton', 'Clementino', 'Clodomiro', 'Clovis', 'Clóvis', 'Conrad', 'Conrado', 'Constantin', 'Constantino', 'Cosme', 'Cristiano', 'Cristóvão', 'Cursino', 'Custódio', 
'Dácio', 'Dagoberto', 'Dalmo', 'Dalton', 'Damião', 'Daniel', 'Danilo', 'Dante', 'Dárcio', 'Dário', 'Darius', 'Davi', 'David', 'Deivid', 'Delfim', 'Delfino', 'Delmar', 'Demétrio', 'Denis', 'Denzel', 'Derik', 'Didier', 'Diego', 'Dilan', 'Dimas', 'Dinis', 'Diniz', 'Dino', 'Diógenes', 'Diogo', 'Dionísio', 'Djalma', 'Dom', 'Domênico', 'Domingos', 'Dominic', 'Donatello', 'Donatílio', 'Donato', 'Donizete', 'Douglas', 'Douglas', 'Durval', 'Dylan', 
'Ed', 'Éder', 'Ederson', 'Edgar', 'Edivaldo', 'Edmilson', 'Edmir', 'Edson', 'Eduardo', 'Eli', 'Elias', 'Eliezer', 'Élio', 'Eliseo', 'Eliseu', 'Elísio', 'Élton', 'Emanuel', 'Emaús', 'Emerson', 'Emílio', 'Ênio', 'Enrico', 'Enrique', 'Enzo', 'Erasmo', 'Erasmus', 'Eriberto', 'Eric', 'Erik', 'Ernesto', 'Esdras', 'Estêvão', 'Eugénio', 'Eurico', 'Evaldo', 'Evandro', 'Evaristo', 'Evelásio', 'Expedito', 'Ezekiel', 
'Fabiano', 'Fábio', 'Fabrício', 'Faustino', 'Fausto', 'Felipe', 'Felisberto', 'Felismino', 'Félix', 'Ferdinand', 'Ferdinando', 'Fernando', 'Fernão', 'Filipe', 'Firmino', 'Flávio', 'Florêncio', 'Florentino', 'Floriano', 'Fortunato', 'Francesco', 'Francis', 'Francisco', 'Franco', 'Frank', 'Franklin', 'Frederico', 
'Gabriel', 'Gael', 'Galdino', 'Galeno', 'Galileu', 'Gaspar', 'Gastão', 'Gaudêncio', 'Genaro', 'Genésio', 'Geovani', 'Geraldo', 'Germano', 'Gerson', 'Giancarlos', 'Giani', 'Gianluca', 'Gil', 'Gilberto', 'Gilmar', 'Gilmar', 'Gilson', 'Giovani', 'Giuseppe', 'Glauco', 'Golias', 'Gonçalo', 'Graciano', 'Gregório', 'Gualter', 'Guarani', 'Guilherme', 'Gumersindo', 'Gustavo', 'Guy', 
'Haroldo', 'Heitor', 'Hélder', 'Hélio', 'Henrique', 'Henry', 'Herbert', 'Hermano', 'Hernâni', 'Horácio', 'Hugo', 'Humberto', 
'Iago', 'Ianis', 'Ícaro', 'Ike', 'Inácio', 'Irineu', 'Isaac', 'Isaías', 'Isidoro', 'Isidro', 'Ismael', 'Israel', 'Ítalo', 'Itamar', 'Ivaldo', 'Ivan', 'Ivandro', 'Ivanildo', 'Ivo', 
'Jacinto', 'Jack', 'Jackson', 'Jader', 'Jadiel', 'Jadir', 'Jaime', 'Jair', 'Jairo', 'Jamal', 'James', 'Jamil', 'Jandir', 'Janilson', 'Januário', 'Jarbas', 'Jason', 'Jason', 'Javier', 'Jean', 'Jefferson', 'Jeremias', 'Jerônimo', 'Jessé', 'Jessie', 'Jessiel', 'Jesualdo', 'Jesus', 'Joab', 'João', 'Joaquim', 'Joel', 'Joelson', 'Jofre', 'Johnny', 'Johnson', 'Jonas', 'Jonatã', 'Jonathan', 'Jorge', 'José', 'Josélio', 'Joshua', 'Josias', 'Josué', 'Juan', 'Juliano', 'Julião', 'Júlio', 'Júnior', 'Jurandir', 'Juvenal', 
'Kaique', 'Kauã', 'Kauan', 'Kawan', 'Kelvin', 'Kennedy', 'Kevin', 'Klaus', 'Kleber', 
'Lael', 'Laerte', 'Laertes', 'Lauro', 'Lázaro', 'Leandro', 'Leon', 'Leonardo', 'Leôncio', 'Leonel', 'Leónidas', 'Leopoldo', 'Levi', 'Lino', 'Lineu', 'Lionel', 'Lisandro', 'Lívio', 'Logan', 'Lorenzo', 'Lourenço', 'Luã', 'Luan', 'Luca', 'Lucas', 'Luciano', 'Lúcio', 'Luigi', 'Luís', 'Luiz', 'Lukas', 'Luzio', 
'Macário', 'Magnus', 'Malvino', 'Manassés', 'Manoel', 'Manuel', 'Maomé', 'Marcelo', 'Márcio', 'Marco', 'Marcos', 'Marcus', 'Mário', 'Marley', 'Marlon', 'Martim', 'Martin', 'Martinho', 'Marvin', 'Mateus', 'Matheo', 'Matheus', 'Mathias', 'Mathieu', 'Matias', 'Maurício', 'Maurílio', 'Mauro', 'Max', 'Maximiliano', 'Maxwell', 'Mélvin', 'Messias', 'Micael', 'Michael', 'Michel', 'Miguel', 'Milo', 'Milton', 'Mizael', 'Moacir', 'Mohamed', 'Moisés', 'Murilo', 
'Nataniel', 'Nazário', 'Neil', 'Nélson', 'Nereu', 'Nestor', 'Newton', 'Ney', 'Nicola', 'Nicolas', 'Nicolau', 'Nildemar', 'Nilo', 'Nilson', 'Nilton', 'Nivaldo', 'Noah', 'Noé', 'Noel', 'Nonato', 'Norberto', 'Norildo', 'Norimar', 'Nuno', 
'Oceano', 'Octávio', 'Odemar', 'Odilson', 'Odin', 'Odorico', 'Olavo', 'Olin', 'Oliver', 'Olivier', 'Omar', 'Omer', 'Onofre', 'Orestes', 'Orlandino', 'Orlando', 'Óscar', 'Osias', 'Osman', 'Osmar', 'Osório', 'Osvaldo', 'Otacílio', 'Otávio', 'Otto', 'Ozael', 
'Pablo', 'Paco', 'Paolo', 'Páris', 'Pascoal', 'Patrício', 'Patrick', 'Paulino', 'Paulo', 'Pedro', 'Pepe', 'Percival', 'Péricles', 'Pierre', 'Porfírio', 
'Querubim', 'Quintino', 
'Radamés', 'Rafael', 'Rafaelo', 'Raí', 'Raimundo', 'Ralf', 'Ralph', 'Ramiro', 'Ramon', 'Ramón', 'Raoni', 'Raphael', 'Raúl', 'Reginaldo', 'Régis', 'Reimão', 'Reinaldo', 'Renan', 'Renato', 'Renê', 'Ricardo', 'Rivaldo', 'Roberto', 'Robson', 'Rodney', 'Rodolfo', 'Rodrigo', 'Roger', 'Rogério', 'Roland', 'Rolando', 'Romão', 'Romário', 'Romeo', 'Romeu', 'Rômulo', 'Ronald', 'Ronaldo', 'Roni', 'Rosendo', 'Rúben', 'Rúbens', 'Rudesindo', 'Rudolfo', 'Rufino', 'Rui', 'Ruy', 'Ryan', 
'Salomão', 'Salvador', 'Samuel', 'Sandro', 'Sansão', 'Santiago', 'Saúl', 'Saulo', 'Sávio', 'Sebastião', 'Selton', 'Serafim', 'Sérgio', 'Sertório', 'Severino', 'Sidney', 'Silas', 'Silvestre', 'Sílvio', 'Simão', 'Simplício', 'Sinésio', 'Stefan', 'Stefano', 'Stenio', 'Steve', 'Steven', 'Sydney', 
'Taciano', 'Tadeu', 'Tales', 'Tamires', 'Tâmiris', 'Tarcísio', 'Tarik', 'Tarsício', 'Telmo', 'Tenório', 'Teo', 'Teobaldo', 'Teodemiro', 'Teodoro', 'Thales', 'Theo', 'Thiago', 'Thomas', 'Thomaz', 'Tiago', 'Tibúrcio', 'Ticiano', 'Tierri', 'Tierry', 'Timóteo', 'Tito', 'Tobias', 'Tom', 'Tomás', 'Tomaz', 'Tomé', 'Tristão', 'Troy', 'Túlio', 
'Ubirajara', 'Ubiratã', 'Ulisses', 'Urbano', 'Uriel', 
'Valdemar', 'Valentim', 'Valentino', 'Válter', 'Vanderlei', 'Vasco', 'Venâncio', 'Veríssimo', 'Vicente', 'Vicenzo', 'Victor', 'Vílmar', 'Vilson', 'Vinício', 'Vinícius', 'Virgílio', 'Vital', 'Vítor', 'Vitório', 'Vladimir', 
'Wagner', 'Waldir', 'Waldo', 'Wallace', 'Walter', 'Washington', 'Watson', 'Webster', 'Weller', 'Wellington', 'Wendel', 'Wesley', 'Will', 'William', 'Wilson', 
'Xavier', 'Xénon', 'Xerxes', 'Xico', 
'Yago', 'Yuri', 'Yves', 
'Zacarias', 'Zack', 'Zaqueu', 'Zayne', 'Zion', 

'Abilio', 'Acacio', 'Adalicio', 'Adelcio', 'Adelio', 'Aderito', 'Aecio', 'Alexio', 'Alexis', 'Alipio', 'Alirio', 'Aloisio', 'Aluisio', 'Alvaro', 'Ambrosio', 'Americo', 'Amilcar', 'Andre', 'Andres', 'Anesio', 'Angelico', 'Anibal', 'Anisio', 'Aprigio', 'Ataide', 'Atila', 'Aurelio', 'Balduino', 'Barnabe', 'Basilio', 'Belisario', 'Benicio', 'Bonifacio', 'Boris', 'Caico', 'Caique', 'Cassio', 'Cesar', 'Cicero', 'Claudio', 'Cristovão', 'Custodio', 'Dacio', 'Darcio', 'Dario', 'Demetrio', 'Diogenes', 'Dionisio', 'Donatilio', 'Eder', 'Elio', 'Elisio', 'Elton', 'Emaus', 'Emilio', 'Eugenio', 'Evelasio', 'Fabio', 'Fabricio', 'Felix', 'Flavio', 'Genesio', 'Gregorio', 'Helder', 'Helio', 'Horacio', 'Icaro', 'Inacio', 'Isaias', 'Italo', 'Januario', 'Jesse', 'Jose', 'Joselio', 'Josue', 'Julio', 'Junior', 'Lazaro', 'Leonidas', 'Livio', 'Lucio', 'Luis', 'Macario', 'Manasses', 'Maome', 'Marcio', 'Mario', 'Mauricio', 'Maurilio', 'Melvin', 'Moises', 'Nazario', 'Nelson', 'Noe', 'Octavio', 'Oscar', 'Osorio', 'Otacilio', 'Otavio', 'Paris', 'Patricio', 'Pericles', 'Porfirio', 'Radames', 'Rai', 'Raul', 'Regis', 'Rogerio', 'Romario', 'Ruben', 'Rubens', 'Saul', 'Savio', 'Sergio', 'Sertorio', 'Silvio', 'Simplicio', 'Sinesio', 'Tarcisio', 'Tarsicio', 'Tenorio', 'Tiburcio', 'Timoteo', 'Tomas', 'Tome', 'Tulio', 'Valter', 'Verissimo', 'Vilmar', 'Vinicio', 'Vinicius', 'Virgilio', 'Vitor', 'Vitorio', 'Xenon', 
'Cadu', 'Chico', 'Dennis', 'Dimitri', 'Fellipe', 'Ian', 'Igor', 'Joao', 'Johnathan', 'Johnatan', 'Lucca', 'Mattias', 'Natan', 'Nathan', 'Nicholas', 'Nycolas', 'Nycholas', 'Peter', 'Philipe', 'Phillipe', 'Raffael', 'Valmir', 'Walmir', 'Yan']


def string_format(name):
    name = name.lower()

    if 'á' in name:
        name = name.replace('á', 'á')

    if 'é' in name:
        name = name.replace('é', 'é')

    if 'í' in name:
        name = name.replace('í', 'í')

    if 'ó' in name:
        name = name.replace('ó', 'ó')

    if 'ú' in name:
        name = name.replace('ú', 'ú')

    if 'â' in name:
        name = name.replace('â', 'â')

    if 'ê' in name:
        name = name.replace('ê', 'ê')

    if 'ô' in name:
        name = name.replace('ô', 'ô')

    if 'ã' in name:
        name = name.replace('ã', 'ã')

    return name.replace("_", '')


